[package]
name = "logentry"
version = "0.1.0"
authors = ["Yuri Geinish <wi1em@protonmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
chrono = { version = "0.4.15", default-features = false }
